SELECT board.TITLE, board.BOARD_ID, reply.REPLY_ID, 
        reply.WRITER_ID, reply.CONTENTS, SUBSTRING(reply.CREATED_DATE, 1, 10) AS CREATED_DATE
FROM USED_GOODS_BOARD board
INNER JOIN USED_GOODS_REPLY reply
    ON reply.BOARD_ID = board.BOARD_ID
WHERE board.CREATED_DATE like "2022-10-%"
ORDER BY reply.CREATED_DATE ASC, board.TITLE ASC;